default: &default
  adapter: postgresql
  host: rds-swe-632.cdyv7dkpcx4v.us-east-1.rds.amazonaws.com
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: xmas_lights
  username: root
  password: <%= ENV['RAILS_DB_PWD'] %>
